# Generated by Django 6.0 on 2026-01-11 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выхода')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'db_table': 'Game',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='Game_title_b97e9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('manufacturer', models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD'), ('Intel', 'Intel')], max_length=10, verbose_name='Производитель')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2007), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выпуска')),
                ('memory_gb', models.IntegerField(verbose_name='Объем памяти (ГБ)')),
                ('memory_type', models.CharField(default='GDDR6', max_length=10, verbose_name='Тип памяти')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя цена (руб)')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
                'db_table': 'Gpu',
                'ordering': ['-release_year', '-name'],
                'indexes': [models.Index(fields=['price_rub'], name='Gpu_price_r_fb99ff_idx'), models.Index(fields=['name'], name='Gpu_name_948269_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('1920x1080', '1920x1080 (Full HD)'), ('2560x1440', '2560x1440 (2K/QHD)'), ('3440x1440', '3440x1440 (UltraWide2K/UWQHD)'), ('3840x2160', '3840x2160 (4K/UHD)')], default='1920x1080', max_length=20, verbose_name='Разрешение')),
                ('graphics_settings', models.CharField(choices=[('low', 'Низкие/low'), ('medium', 'Средние/medium'), ('high', 'Высокие/high'), ('ultra', 'Ультра/ultra')], default='medium', max_length=20, verbose_name='Настройки графики')),
                ('avg_fps', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средний FPS')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='core.game', verbose_name='Игра')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='core.gpu', verbose_name='Видеокарта')),
            ],
            options={
                'verbose_name': 'Тест производительности',
                'verbose_name_plural': 'Тесты производительности',
                'db_table': 'PerformanceData',
                'ordering': ['-avg_fps'],
                'indexes': [models.Index(fields=['gpu', 'game'], name='Performance_gpu_id_f35d87_idx'), models.Index(fields=['resolution', 'graphics_settings'], name='Performance_resolut_f1ae2e_idx')],
                'unique_together': {('gpu', 'game', 'resolution', 'graphics_settings')},
            },
        ),
    ]
