# Generated by Django 6.0 on 2026-01-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='memory_type',
        ),
    ]
