# Generated by Django 6.0 on 2025-12-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gpu',
            new_name='Gpu_price_r_fb99ff_idx',
            old_name='GPU_price_r_dead50_idx',
        ),
        migrations.AlterModelTable(
            name='gpu',
            table='Gpu',
        ),
    ]
