# Generated by Django 6.0 on 2025-12-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_gpu_price_r_dead50_idx_gpu_price_r_fb99ff_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='URL'),
        ),
    ]
